FROM docker.io/openjdk:20-slim-buster AS build
COPY ./Tienda/Cliente.java ./Tienda/Articulo.java ./Tienda/InterfazMetodos.java /home/
WORKDIR /home
RUN javac *.java && apt-get update && apt-get install -y iputils-ping net-tools
ENTRYPOINT [ "java", "Cliente" ]