name: Build Container Image

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile-client
  schedule:
    - cron: "0 0 * * */15"
  workflow_dispatch:

env:
 REGISTRY: docker.io
 IMAGE_NAME: rmi-client-example
 USERNAME:  ${{ github.actor }}

concurrency:
  group: build-${{ github.event.push.number || github.ref }}
  cancel-in-progress: true

jobs:
 client_container_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build and Push Latest Docker Image
        id: build-and-push-latest
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-client
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}